---
- name: Install and Configure remote service vm
  hosts: all
  tasks:
    - name: Copy private key to remote hosts
      ansible.builtin.copy:
        src: "~/.ssh/netology"
        dest: "~/.ssh/netology"
        mode: "600"
    - name: Copy public key to remote hosts
      ansible.builtin.copy:
        src: "~/.ssh/netology.pub"
        dest: "~/.ssh/netology.pub"
        mode: "600"
