#cloud-config
ssh_pwauth: no
users:
  - name: dotsenkois
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL    
    passwd: $6$rounds=4096$2lnfl.BvbQyhFZDJ$uSLTNFXlqGV0kf6nIiE3nMJHJ.XPch5WF5OWg2T5tw8qSw3yNvNTMtKepItJowUM.emgaYd1baoyoLQI6GPgJ/
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcdF/ZrY6ot17fMyUBwaw9eVcYvKu53emT2/AylArwh/sPd8hQJxktBT41Uu7oLQsIdt0v0ZtosSQFUSJPXfNFnlpUHPlT7/BRbfigIlvlGwqGF7uq3SrlKJKDI0S5+RDEdO3tFnGlNHuUiHwrMGzWabU7qNae/dSX6LPA7aJc38B3J8ZF22mFL01/qdpkN6lkQWdoILhK9EskdD2XPu4JeTpND+/IXMMpTPf8rhkWL0+rb3MdLyXnPa44fMpd9UYLwUVd9QIV96pXskso+VC6NZHCNH6YXLuP6XxrQr7PAph1lIu0MqhAzLELx/N6A10BLoNiI+cas79KEjR+rNghH6w/DH65z5cecJYFmqpqv4buIobLRHas8s00047M+PLqKyGqL9zfUWIkbjDNd7fp1iNieKEKCY5lPMNIG1Y6o5zZSlc3tOPQ2VNB67QsamC+jxX0rL2weIEvSzR3eb4wDNJGDPZC9rOJb0BQ0MKs8UUpMhw+cCRlXOI+L4kzuYk= dotsenkois@dotsenkois-vm
    primary_group: dotsenkois
    groups: root
packages_update: true
packages_upgrade: true
runcmd:
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install postgresql-14 libpq-dev postgresql-contrib
  - wget https://raw.githubusercontent.com/dotsenkois/diploma-web-app/main/docker/postgres/init.sql -O ~/init.sql
  - sudo --user=postgres psql < ~/init.sql
  - sudo wget https://raw.githubusercontent.com/dotsenkois/diploma-web-app/main/docker/postgres/my.conf -O /etc/postgresql/14/main/conf.d/my.conf
  - sudo echo "host    netology     dotsenkois             192.168.10.0/24            scram-sha-256 " >> /etc/postgresql/14/main/pg_hba.conf
  - sudo echo "host    netology     dotsenkois             51.250.14.227/32            scram-sha-256 " >> /etc/postgresql/14/main/pg_hba.conf
  - sudo systemctl restart postgresql
  
packages:
  net-tools