---
version: "3"
services:
  jenkins-docker:
    image: docker:dind
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    environment:
      DOCKER_TLS_CERTDIR: /certs
    ports:
      - 2376:2376
    networks:
      jenkins:

  jenkins-blueocean:
    image: jenkinsci/blueocean
    depends_on:
      - jenkins-docker
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - 8080:8080
      - 50000:50000 
    networks:
      jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins: