---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stage
  name: backend
  # namespace: prod
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cr.yandex/crpie94if7p5bh3bbf51/diploma-web-app_backend:0.1.1
          ports:
          - containerPort: 8000
          env:
            - name: DB_NAME
              value: netology
            - name: DB_USER
              value: dotsenkois
            - name: DB_PASSWORD
              value: "12345678"
            - name: HOST
              value: 192.168.10.100          
            - name: PORT
              value: "5432"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stage
spec:
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
  selector:
    app: backend
  type: ClusterIP
