resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

---
all:
  hosts:
    teamcity-server:
      ansible_host: ${yandex_compute_instance.teamcity-server.network_interface.0.nat_ip_address}
    teamcity-agent:
      ansible_host: ${yandex_compute_instance.teamcity-agent.network_interface.0.nat_ip_address}
    nexus:
      ansible_host: ${yandex_compute_instance.nexus.network_interface.0.nat_ip_address}

  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            teamcity-server:
        jenkins_agents:
          hosts:
              teamcity-agent:
        nexus:
          hosts:
            nexus:
      
  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois
    DOC
  filename = "../infrastructure/inventory/cicd/hosts.yml"
  

  depends_on = [
    yandex_compute_instance.teamcity-server,
    yandex_compute_instance.teamcity-agent,
    yandex_compute_instance.nexus
  ]
}