---
- name: Service-instance-prepare
  hosts: service-instance-001
  tasks:
    - name: Copy id_rsa
      ansible.builtin.copy:
        src: ../../dotsenkois
        dest: /home/dotsenkois/.ssh/id_rsa
        force: true
        mode: "644"
    - name: Copy web app
      ansible.builtin.copy:
        src: ../../diploma-web-app/
        dest: /home/dotsenkois/diploma-web-app/
        force: true
        mode: "744"
