#cloud-config
version: v1
ssh_pwauth: no
packages_update: true
packages_upgrade: true
packages:
  - git
  - docker-compose
  - htop
  - docker.io
  - python3-pip
  - net-tools
  - unzip
  - zip
  - apt-transport-https
  - postgresql-client-common
  - jq
  - jsonnet
users:
  - name: ubuntu
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL    
    lock_passwd: false
    passwd: $6$rounds=4096$7SUAIMSGEVz7PUb4$6xyaI.DarGCS8X4Qb1fmrxEPx2DVTxTdcNJQgU1gVQINgTglIrgs2XBJ5NVIs7K8N2XBxWBShAXvyx1PeqwJI/
    primary_group: ubuntu
    groups: root, docker
runcmd:
  - sleep 120
  - echo "alias k=kubectl" >> ~/.bashrc 
  - echo "source <( kubectl completion bash | sed s/kubectl/k/g )" >> ~/.bashrc 
  - echo "source <( kubectl completion bash )" >> ~/.bashrc 
  - [ pip, install, ansible ]
  - if [ ! -f /usr/bin/terraform ]; then wget https://storage.yandexcloud.net/bucket-sa-distrib1/terraform_1.3.3_linux_amd64.zip -O /tmp/terraform.zip && sudo unzip /tmp/terraform.zip /usr/bin/terraform; fi
  - if [ ! -f /usr/local/bin/helm ]; then curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash; fi
  - if [ ! -f /usr/bin/qbec ]; then wget https://github.com/splunk/qbec/releases/download/v0.15.2/qbec-linux-amd64.tar.gz -O /tmp/qbec-linux-amd64.tar.gz && sudo tar zxvf /tmp/qbec-linux-amd64.tar.gz -C /usr/bin/; fi
  - qbec completion | sudo tee /etc/bash_completion.d/qbec
  - if [ ! -f /usr/bin/kubectl ]; then curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && sudo mv kubectl /usr/bin/kubectl; fi
  - mkdir ~/repo

  # - [ git, clone ,"https://github.com/dotsenkois/diploma-yandexcloud.git" ]
  # - [ git, clone ,"https://github.com/dotsenkois/diploma-web-app.git" ]
  # - wget "https://storage.yandexcloud.net/bucket-sa-distrib1/terraform_1.3.3_linux_amd64.zip" -O "/tmp/terraform.zip" && sudo unzip /tmp/terraform.zip -d /usr/bin/