#cloud-config
version: v1
ssh_pwauth: no
# packages_update: true
# packages_upgrade: true
# packages:
#  - git
#  - docker-compose
#  - docker.io
#  - python3-pip
#  - htop
#  - net-tools
#  - unzip
#  - zip
#  - postgresql-client-common
#  - jq
#  - jsonnet
users:
  - name: dotsenkois
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL    
    lock_passwd: false
    passwd: $6$rounds=4096$7SUAIMSGEVz7PUb4$6xyaI.DarGCS8X4Qb1fmrxEPx2DVTxTdcNJQgU1gVQINgTglIrgs2XBJ5NVIs7K8N2XBxWBShAXvyx1PeqwJI/
    primary_group: dotsenkois
    groups: root, docker
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3bXWZ0ilGnNS1Q1VMO06WScGKTIDUV0jlIdT88h+rnN3WBayAofWpIT/KViArFRk4/IKkghwPHllos9MF2UPEiUz9qdGjxJdSxey6WWVwCf1GmENQivUBklSZX1MP3SThwFk1TRpWnrW/+od0fpRZbTRJLuLKWUhDacVe7xNTVWp+LhnITKEzkAqOdizkLoXeI2+GkJnrjnkWU0H4yno1US97mFnQh0A/R7Say16Q5KXUtex5caoShOsOeKcGj71OkBoKWRMN5AZ+kvgk+FOJcZ3YF8245dtATmBPejlJsjv4xHaCtg48kJfRKRzcJPZcZOM0hplTkMzcUA2Bav438kDZuTFE8nM2PlDLRuTOdeUHh4+nWxEl3cjzN2+0rh5mRDClQMgnt1oTyCqIASXr5rm6m3NKJrz441SOyi0ZFHt2G7qEJg3GQhNu5OjnSYeDTzK0kC9ztytC/rMyVMmIkz7v4O/4SCQuj0H65uLaVtVKYUj0VKinAS9fm8tFDXE= dotsenkois@dotsenkois-vm
runcmd:
  - echo "alias k=kubectl" >> ~/.bashrc 
  - echo "source <( kubectl completion bash | sed s/kubectl/k/g )" >> ~/.bashrc 
  - echo "source <( kubectl completion bash )" >> ~/.bashrc 

  # - sleep 60  
  # - [ pip, install, ansible ]
  # - [ git, clone ,"https://github.com/dotsenkois/diploma-yandexcloud.git" ]
  # - [ git, clone ,"https://github.com/dotsenkois/diploma-web-app.git" ]
  # - wget "https://storage.yandexcloud.net/bucket-sa-distrib1/terraform_1.3.3_linux_amd64.zip" -O "/tmp/terraform.zip" && sudo unzip /tmp/terraform.zip -d /usr/bin/