#cloud-config
version: v1
ssh_pwauth: no
packages_update: true
packages_upgrade: true
packages:
 - git
 - docker-compose
 - docker.io
 - python3-pip
 - htop
 - net-tools
users:
  - name: dotsenkois
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: $6$rounds=4096$7SUAIMSGEVz7PUb4$6xyaI.DarGCS8X4Qb1fmrxEPx2DVTxTdcNJQgU1gVQINgTglIrgs2XBJ5NVIs7K8N2XBxWBShAXvyx1PeqwJI/
    primary_group: dotsenkois
    groups: root, docker
bootcmd:
  - [ wget, "https://storage.yandexcloud.net/bucket-sa-distrib1/terraform_1.3.3_linux_amd64.zip", -O, "/tmp/terraform.zip" ]
  - sudo unzip /tmp/terraform.zip -d /usr/bin/
  - [ pip, install, ansible ]
  - [ git, clone ,"https://github.com/dotsenkois/diploma-yandexcloud.git" ]
  - [ git, clone ,"https://github.com/dotsenkois/diploma-web-app.git" ]
