---
all:
  hosts:
# db-master
    db-master-001:
      ansible_host: 51.250.74.121
# db-slave
# service-instance
    service-instance-001:
      ansible_host: 51.250.77.79
# nat
    nat:
      ansible_host: 62.84.113.87

  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois


etcd_cluster:
  hosts:
    db-master-001:
      ansible_host: 51.250.74.121

balancers:
  hosts:
    db-master-001:
      ansible_host: 51.250.74.121

postgres_cluster:
  children:
    master:
      hosts:
    db-master-001:
    replica:
      hosts:

service-instance:
  children:
    service-instance:
    service-instance-001:
      ansible_host: 51.250.77.79

