---
all:
  hosts:
# db-master
    db-master-001:
      ansible_host: 51.250.85.187
# db-slave

# nat
    nat:
      ansible_host: 51.250.72.1

  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois


etcd_cluster:
  hosts:
    db-master-001:
      ansible_host: 51.250.85.187

balancers:
  hosts:
    db-master-001:
      ansible_host: 51.250.85.187

postgres_cluster:
  children:
    master:
      hosts:
    db-master-001:
    replica:
      hosts:

