---
all:
  hosts:
# db-master
    db-master-001:
      ansible_host: 84.201.175.97
# db-slave

# nat
    nat:
      ansible_host: 62.84.113.87

  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois


etcd_cluster:
  hosts:
    db-master-001:
      ansible_host: 84.201.175.97

balancers:
  hosts:
    db-master-001:
      ansible_host: 84.201.175.97

postgres_cluster:
  children:
    master:
      hosts:
    db-master-001:
    replica:
      hosts:

