---
all:
  hosts:
# db-master
    db-master-001:
      ansible_host: 178.154.252.130
# db-slave

# nat
    nat:
      ansible_host: 51.250.87.39

  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois


etcd_cluster:
  hosts:
    db-master-001:
      ansible_host: 178.154.252.130

balancers:
  hosts:
    db-master-001:
      ansible_host: 178.154.252.130

postgres_cluster:
  children:
    master:
      hosts:
    db-master-001:
    replica:
      hosts:

