---
all:
  hosts:
# db-master
    db-master-001:
      ansible_host: 178.154.222.37
# db-slave
# service-instance
    service-instance-001:
      ansible_host: 51.250.5.243
# nat
    nat:
      ansible_host: 178.154.227.141

  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois


etcd_cluster:
  hosts:
    db-master-001:
      ansible_host: 178.154.222.37

balancers:
  hosts:
    db-master-001:
      ansible_host: 178.154.222.37

postgres_cluster:
  children:
    master:
      hosts:
    db-master-001:
    replica:
      hosts:

service-instance:
  children:
    service-instance:
    service-instance-001:
      ansible_host: 51.250.5.243

