---
all:
  hosts:
# db-master
    db-master-001:
      ansible_host: 51.250.10.240
# db-slave

# nat
    nat:
      ansible_host: 51.250.95.131

  vars:
    ansible_connection_type: paramiko
    ansible_user: dotsenkois


etcd_cluster:
  hosts:
    db-master-001:
      ansible_host: 51.250.10.240

balancers:
  hosts:
    db-master-001:
      ansible_host: 51.250.10.240

postgres_cluster:
  children:
    master:
      hosts:
    db-master-001:
    replica:
      hosts:

